name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark

      - name: Upload Generated Files
        uses: actions/upload-artifact@v3.1.2  # Use explicit version to avoid missing download info
        with:
          name: snake-animation
          path: |
            github-snake.svg
            github-snake-dark.svg  # Ensure both files are uploaded

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use PAT for push access
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git checkout main  # Ensure we are on the main branch
          git add github-snake.svg github-snake-dark.svg
          git diff --cached --quiet || (git commit -m "Updated snake animation" && git push origin main)
