name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:      # Allow manual triggers

permissions:
  contents: write  # Necessary for pushing changes

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: List Generated Files (Debug)
        run: ls -R dist/ || echo "No files generated"

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Use a Personal Access Token
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git

          # Check if SVGs exist in dist/ before committing
          if [ -f dist/github-snake.svg ] && [ -f dist/github-snake-dark.svg ]; then
            git add dist/github-snake.svg dist/github-snake-dark.svg
            git commit -m "Updated snake animation in dist/"
            git push origin main
          else
            echo "SVG files not found in dist/, skipping commit."
            exit 1  # Exit with error to indicate failure
          fi
